#!/usr/bin/env python3
"""
Generate the Wuji-hand gravity-compensation URDFs
=================================================
Rewrites nerolib/urdf/{nero_cone-e_left_fixed,right_arm_final}_wuji.urdf from
their no-hand base URDFs by

  1. correcting joint7's rpy (see JOINT7_RPY below), and
  2. appending everything distal to link7 -- the stand_v2 end effector, the
     wuji_nero_mount and the Wuji hand -- as one lumped rigid payload.

The lumped mass/CoM/inertia constants were computed once from
YOR-v3-try/description/robot_wholebody.xml with MuJoCo (subtree mass, CoM, and
inertia about the CoM, expressed in the link7 body frame) and are embedded
below, so this script runs anywhere without MuJoCo or that model.

MuJoCo derives the hand's mass from mesh volume at the default density, giving
0.476 kg -- well under the real hand, whose datasheet weight is 580 +/- 10 g
excluding cables (Wuji Hand 2 is 745 g). Under-modelling the hand leaves
uncompensated torque at the shoulder, which both makes the arm sag and keeps
homing from settling inside its position tolerance. So the hand mass is a
parameter here: pass the weight of the hand actually bolted on, including
whatever cabling it carries.

  ./make_wuji_urdf.py                      # 0.58 kg, stock Wuji Hand
  ./make_wuji_urdf.py --hand-mass 0.745    # Wuji Hand 2
  ./make_wuji_urdf.py --hand-mass 0.62     # stock hand + ~40 g of cable

Inertia is scaled with the mass (same geometry, higher density); the CoM is
unchanged, which is the right correction when the mesh is the right shape but
the uniform density is too low.
"""

import argparse
import re
from pathlib import Path

import numpy as np

# Datasheet weight of a stock Wuji Hand, excluding cables.
DEFAULT_HAND_MASS = 0.58

# joint7's rpy in the base URDFs does not match the MJCF: URDF rpy is extrinsic
# ZYX while MuJoCo euler is intrinsic xyz, and the two files were reconciled by
# copying the numbers across. The value below is the correct conversion of the
# MJCF's euler="1.5708 0 -1.5708", verified numerically against
# robot_wholebody.xml. The base URDFs put joint7's axis perpendicular to the
# real wrist-roll axis, which is harmless while link7 is massless but wrong the
# moment a hand hangs off it.
JOINT7_RPY = "-2.356194 1.570791 2.356194"

# Lumped inertials in the link7 frame. Inertia is (ixx, ixy, ixz, iyy, iyz, izz)
# about each part's own CoM. FIXED is the stand_v2 end effector plus the
# wuji_nero_mount, whose masses are modelled explicitly and so are trusted as
# is; HAND is the palm and all twenty finger links, whose mass is rescaled.
FIXED = {
    "mass": 0.130000,
    "com": (-0.004646, 0.044904, -0.023377),
    "inertia": (4.897508e-05, -7.340923e-06, 1.189661e-07,
                5.760320e-05, 1.945017e-07, 5.128197e-05),
}
HAND = {
    "left": {
        "mass": 0.476076,
        "com": (-0.007071, 0.164916, -0.016693),
        "inertia": (1.964160e-03, 1.816041e-04, -8.595284e-05,
                    7.395270e-04, 2.201912e-04, 1.327616e-03),
    },
    "right": {
        "mass": 0.476023,
        "com": (-0.006995, 0.165357, -0.030321),
        "inertia": (1.991129e-03, 1.835704e-04, 8.650317e-05,
                    7.416298e-04, -2.152235e-04, 1.350942e-03),
    },
}

BASE_URDF = {
    "left": "nero_cone-e_left_fixed.urdf",
    "right": "right_arm_final.urdf",
}
OUT_URDF = {
    "left": "nero_cone-e_left_fixed_wuji.urdf",
    "right": "right_arm_final_wuji.urdf",
}


def _tensor(flat):
    ixx, ixy, ixz, iyy, iyz, izz = flat
    return np.array([[ixx, ixy, ixz], [ixy, iyy, iyz], [ixz, iyz, izz]])


def combine(side, hand_mass):
    """Lump the fixed hardware and the rescaled hand into one rigid body."""
    hand = HAND[side]
    scale = hand_mass / hand["mass"]

    parts = [
        (FIXED["mass"], np.array(FIXED["com"]), _tensor(FIXED["inertia"])),
        (hand_mass, np.array(hand["com"]), _tensor(hand["inertia"]) * scale),
    ]

    total = sum(mass for mass, _, _ in parts)
    com = sum(mass * c for mass, c, _ in parts) / total

    inertia = np.zeros((3, 3))
    for mass, c, i_local in parts:
        r = c - com
        inertia += i_local + mass * ((r @ r) * np.eye(3) - np.outer(r, r))
    return total, com, inertia


def payload_block(side, hand_mass):
    mass, com, inertia = combine(side, hand_mass)
    return f"""
  <!-- WUJI HAND PAYLOAD (generated by scripts/make_wuji_urdf.py -- edit there,
       not here). Everything distal to link7 lumped into one rigid body: the
       stand_v2 end effector, the wuji_nero_mount, and the {side} Wuji hand with
       its fingers at qpos0, taken as {hand_mass:.3f} kg. Pinocchio absorbs the
       fixed joint into link7 automatically. -->
  <link name="wuji_hand_payload">
    <inertial>
      <origin xyz="{com[0]:.6f} {com[1]:.6f} {com[2]:.6f}" rpy="0 0 0" />
      <mass value="{mass:.6f}" />
      <inertia ixx="{inertia[0, 0]:.6e}" ixy="{inertia[0, 1]:.6e}" ixz="{inertia[0, 2]:.6e}"
               iyy="{inertia[1, 1]:.6e}" iyz="{inertia[1, 2]:.6e}" izz="{inertia[2, 2]:.6e}" />
    </inertial>
  </link>
  <joint name="link7_to_wuji_hand" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="link7" />
    <child link="wuji_hand_payload" />
  </joint>

</robot>"""


def fix_joint7(text, side):
    """Point joint7's axis along the real wrist-roll axis."""
    pattern = re.compile(
        r'(<joint name="joint7" type="revolute">\s*<origin xyz="[^"]*" rpy=")[^"]*(")'
    )
    text, n = pattern.subn(rf"\g<1>{JOINT7_RPY}\g<2>", text)
    if n != 1:
        raise SystemExit(f"{side}: expected exactly one joint7 origin, found {n}")

    # The base URDF carries a note saying its joint7 rpy is *not* the MJCF
    # orientation. That is true there and false here, so replace it rather
    # than copying a statement the generated file contradicts.
    note = re.compile(r"[ \t]*<!--\s*NOTE: joint7's rpy below is NOT.*?-->\n", re.DOTALL)
    text = note.sub(
        "  <!-- joint7 rpy set by scripts/make_wuji_urdf.py: the extrinsic-ZYX\n"
        "       equivalent of the MJCF's intrinsic-xyz euler='1.5708 0 -1.5708'. -->\n",
        text,
    )
    return text


def generate(urdf_dir, side, hand_mass):
    base = urdf_dir / BASE_URDF[side]
    out = urdf_dir / OUT_URDF[side]
    text = fix_joint7(base.read_text(), side)

    tail = text.rstrip()
    if not tail.endswith("</robot>"):
        raise SystemExit(f"{base}: does not end with </robot>")
    text = tail[: -len("</robot>")].rstrip() + "\n" + payload_block(side, hand_mass)

    out.write_text(text)
    mass, com, _ = combine(side, hand_mass)
    print(f"[MakeWujiURDF] {out.name}: payload {mass:.4f} kg, "
          f"com {np.round(com, 4).tolist()} (link7 frame)")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--hand-mass", type=float, default=DEFAULT_HAND_MASS,
                        help="mass of one Wuji hand in kg, cables included "
                             f"(default {DEFAULT_HAND_MASS}, the datasheet weight)")
    parser.add_argument("--urdf-dir", type=Path,
                        default=Path(__file__).resolve().parent.parent / "urdf",
                        help="nerolib urdf directory to read from and write to")
    args = parser.parse_args()

    if not np.isfinite(args.hand_mass) or args.hand_mass <= 0.0:
        raise SystemExit("--hand-mass must be finite and positive")

    for side in ("left", "right"):
        generate(args.urdf_dir, side, args.hand_mass)
