
if(NOT TARGET urdfdom::urdfdom)
  find_package(PkgConfig REQUIRED)
  pkg_check_modules(urdfdom REQUIRED urdfdom)

  add_library(urdfdom::urdfdom INTERFACE IMPORTED)
  target_include_directories(urdfdom::urdfdom INTERFACE ${urdfdom_INCLUDE_DIRS})
  target_link_libraries(urdfdom::urdfdom INTERFACE ${urdfdom_LIBRARIES})
  target_link_directories(urdfdom::urdfdom INTERFACE ${urdfdom_LIBRARY_DIRS})
  target_link_options(urdfdom::urdfdom INTERFACE ${urdfdom_LDFLAGS})

  set(urdfdom_FOUND TRUE)
  
  if(NOT TARGET urdfdom::urdf_parser)
    add_library(urdfdom::urdf_parser ALIAS urdfdom::urdfdom)
  endif()
  if(NOT TARGET urdfdom::urdf_model_state)
    add_library(urdfdom::urdf_model_state ALIAS urdfdom::urdfdom)
  endif()
  if(NOT TARGET urdfdom::urdf_model)
    add_library(urdfdom::urdf_model ALIAS urdfdom::urdfdom)
  endif()
  if(NOT TARGET urdfdom::urdf_world)
    add_library(urdfdom::urdf_world ALIAS urdfdom::urdfdom)
  endif()
  if(NOT TARGET urdfdom::urdf_sensor)
    add_library(urdfdom::urdf_sensor ALIAS urdfdom::urdfdom)
  endif()
endif()
